"""Generate the winget manifests for the current release.

Run it *after* the installer has been built, so the manifests carry the real
SHA256 of the exact bytes that will be published:

    .venv/Scripts/python.exe tools/make_winget.py

It reads ``constants.APP_VERSION`` and the installer(s) in ``dist/``, writes

    winget/manifests/a/AnujSharma/AIVoiceStudio/<version>/
        AnujSharma.AIVoiceStudio.yaml
        AnujSharma.AIVoiceStudio.installer.yaml
        AnujSharma.AIVoiceStudio.locale.en-US.yaml

and verifies them with ``tools/winget_validate.py`` in the same run.  The
folder copies straight into the ``microsoft/winget-pkgs`` repository when the
release is published (see ``winget/README.md``).

Options:
    --version X.Y.Z      override the version (default: APP_VERSION)
    --arch x64 x86       which installer(s) to publish (default: those built)
    --notes "..."        one-line release note for the locale manifest
    --date YYYY-MM-DD    release date (default: today)
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import winget_manifests as wm  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


def _app_version() -> str:
    from ai_voice_studio.constants import APP_VERSION

    return APP_VERSION


def _hashes(version: str, arches: list) -> tuple:
    """Existing installers in ``dist/`` with their hashes, and the missing ones."""
    sha256 = {}
    exists = {}
    for arch in arches:
        path = wm.installer_path(ROOT, version, arch)
        exists[arch] = os.path.isfile(path)
        if exists[arch]:
            sha256[arch] = wm.file_sha256(path)
    return sha256, exists


def write(version: str, sha256: dict, notes: str, release_date: str) -> list:
    folder = wm.manifest_dir(ROOT, version)
    os.makedirs(folder, exist_ok=True)
    manifests = wm.build_all(version, sha256, release_date, notes)
    written = []
    for name, data in manifests.items():
        path = os.path.join(folder, name)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("# Generated by tools/make_winget.py - do not edit by hand.\n")
            handle.write(f"# Package: {wm.PACKAGE_NAME} {version}\n")
            handle.write(wm.dump_yaml(data) + "\n")
        written.append(path)
    return written


def main(argv: list) -> int:
    import winget_validate  # noqa: PLC0415 - shares the same folder

    version = _app_version()
    arches = list(wm.ARCHITECTURES)
    notes = ""
    release_date = ""

    index = 1
    while index < len(argv):
        arg = argv[index]
        if arg == "--version" and index + 1 < len(argv):
            version = argv[index + 1]
            index += 2
        elif arg == "--arch" and index + 1 < len(argv):
            arches = [a.strip() for a in argv[index + 1].split(",") if a.strip()]
            index += 2
        elif arg == "--notes" and index + 1 < len(argv):
            notes = argv[index + 1]
            index += 2
        elif arg == "--date" and index + 1 < len(argv):
            release_date = argv[index + 1]
            index += 2
        else:
            print(f"Unknown argument: {arg}")
            return 2

    sha256, exists = _hashes(version, arches)
    if not sha256:
        print("No installer found in dist/ for version " + version + ".")
        print("Build first:  powershell -ExecutionPolicy Bypass -File packaging\\build.ps1 -Arch x64")
        return 1

    written = write(version, sha256, notes, release_date)
    print(f"Wrote {len(written)} manifest(s) for {wm.PACKAGE_NAME} {version}:")
    for path in written:
        print("  " + os.path.relpath(path, ROOT))
    for arch in arches:
        state = sha256.get(arch, "(not built - not published)")
        print(f"  {arch}: {state}")
    for arch in arches:
        if not exists.get(arch):
            print(f"  note: no {arch} installer in dist/ yet, so {arch} is not in the manifest.")

    problems = winget_validate.check(version, root=ROOT)
    if problems:
        print("\nManifest validation found problems:")
        for problem in problems:
            print("  ! " + problem)
        return 1
    print("\nManifest validation: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
