"""The winget manifests for AI Voice Studio, and the rules they must satisfy.

winget (the Windows Package Manager) describes a package with **three YAML
documents** kept in the ``winget-pkgs`` repository under

    manifests/<first letter>/<Publisher>/<Package>/<Version>/

* ``<PackageIdentifier>.yaml`` - the version manifest,
* ``<PackageIdentifier>.installer.yaml`` - what to download and how to run it
  silently,
* ``<PackageIdentifier>.locale.<locale>.yaml`` - the human-readable metadata.

This module owns that description in one place so the generator
(``make_winget.py``), the checker (``winget_validate.py``) and the test suite
all agree on it, and so the version in the manifests cannot drift away from
``constants.APP_VERSION``.

It also carries a very small YAML writer and reader for exactly the subset
winget manifests use (maps, lists of maps, single-line scalars, comments).
The project deliberately does not depend on PyYAML: the manifests are
generated by us and read back by us, so a 100-line reader with no install
footprint is a better trade than a new runtime dependency.
"""

from __future__ import annotations

import hashlib
import os
import re
from datetime import date, datetime

# ---------------------------------------------------------------------------
# The package identity
# ---------------------------------------------------------------------------
PACKAGE_IDENTIFIER = "AnujSharma.AIVoiceStudio"
PUBLISHER = "Anuj Sharma"
AUTHOR = "Anuj Sharma"
PACKAGE_NAME = "AI Voice Studio"
MONIKER = "aivoicestudio"
LICENSE = "GPL-3.0-or-later"
COPYRIGHT = "Copyright (c) Anuj Sharma"
PROJECT_URL = "https://github.com/anujj87/AIVoiceStudio"
PUBLISHER_URL = "https://github.com/anujj87"
SUPPORT_URL = f"{PROJECT_URL}/issues"
LICENSE_URL = f"{PROJECT_URL}/blob/main/LICENSE"
RELEASES_URL = f"{PROJECT_URL}/releases"
LOCALE = "en-US"

# The manifest schema both winget and the winget-pkgs submission pipeline
# accept today.
MANIFEST_VERSION = "1.6.0"

INSTALLER_TYPE = "inno"
ARCHITECTURES = ("x64", "x86")

# The Inno Setup AppId (packaging/installer_common.iss).  Inno appends
# "_is1" when it creates the entry in "Apps and features", and that value is
# the ProductCode winget uses to detect an existing installation.
INNO_APP_ID = "{D9B4E3A0-7A1E-4E8B-9C2F-AIVOICESTUDIO01}"
PRODUCT_CODE = INNO_APP_ID + "_is1"

# Inno Setup's own silent switches.  /VERYSILENT is also what winget passes.
SILENT_SWITCH = "/VERYSILENT"
SILENT_WITH_PROGRESS_SWITCH = "/SILENT"
CUSTOM_SWITCH = "/NORESTART"

SHORT_DESCRIPTION = (
    "Convert PDF, DOCX, EPUB and clipboard text into spoken audio with "
    "offline neural voices"
)
DESCRIPTION = (
    "AI Voice Studio turns documents into spoken audio books and DAISY "
    "talking books on your own computer. It reads PDF, DOC/DOCX, EPUB, "
    "HTML, Markdown and plain text (or text on the clipboard), splits the "
    "text into pages or chapters, and records each part as a separate "
    "WAV, MP3 or FLAC file with an offline neural text-to-speech engine. "
    "Every window works with a screen reader: real MSAA names on every "
    "control, access keys on every action, keyboard-only operation, and an "
    "audit tool that fails the build when a gesture stops working. "
    "Synthesis runs locally, so no document leaves the machine."
)
TAGS = (
    "tts",
    "text-to-speech",
    "speech-synthesis",
    "accessibility",
    "screen-reader",
    "audiobook",
    "daisy",
    "offline",
    "voice-cloning",
    "python",
)
SHORT_DESCRIPTION_MAX = 256
DESCRIPTION_MIN, DESCRIPTION_MAX = 3, 10000

_SHA256_RE = re.compile(r"^[0-9A-F]{64}$")
_IDENTIFIER_RE = re.compile(r"^[A-Za-z0-9]+([.\-][A-Za-z0-9]+)*$")
_VERSION_RE = re.compile(r"^\d+(\.\d+){1,3}$")
_TAG_RE = re.compile(r"^[a-z0-9]+([+\-.][a-z0-9]+)*$")


# ---------------------------------------------------------------------------
# Names and URLs
# ---------------------------------------------------------------------------
def release_tag(version: str) -> str:
    """``2026.3.7`` -> ``v2026.3.7`` (the Git tag the release pipeline uses)."""
    return "v" + str(version).strip()


def dashed_version(version: str) -> str:
    """``2026.3.7`` -> ``2026-3-7`` (dots are not allowed in file names)."""
    return str(version).strip().replace(".", "-")


def installer_filename(version: str, arch: str = "x64") -> str:
    """The installer name ``packaging/build.ps1`` produces."""
    return f"AI-Voice-Studio-v-{dashed_version(version)}-Setup-{arch}.exe"


def installer_url(version: str, arch: str = "x64") -> str:
    """The *stable, versioned* download URL of that installer."""
    return (
        f"{RELEASES_URL}/download/{release_tag(version)}/"
        f"{installer_filename(version, arch)}"
    )


def manifest_dir(root: str, version: str) -> str:
    """The ``manifests/a/AnujSharma/AIVoiceStudio/<version>`` folder."""
    letter = PACKAGE_IDENTIFIER[0].lower()
    return os.path.join(
        root, "winget", "manifests", letter, "AnujSharma", "AIVoiceStudio",
        str(version),
    )


def installer_path(root: str, version: str, arch: str = "x64") -> str:
    """Where the built installer for this version lives (``dist/``)."""
    return os.path.join(root, "dist", installer_filename(version, arch))


def file_sha256(path: str) -> str:
    """Uppercase SHA256 of a file, the form winget requires."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


# ---------------------------------------------------------------------------
# The three manifests
# ---------------------------------------------------------------------------
def version_manifest(version: str) -> dict:
    return {
        "PackageIdentifier": PACKAGE_IDENTIFIER,
        "PackageVersion": str(version),
        "DefaultLocale": LOCALE,
        "ManifestType": "version",
        "ManifestVersion": MANIFEST_VERSION,
    }


def installer_manifest(version: str, sha256: dict, release_date: str = "",
                       urls: dict | None = None) -> dict:
    """The installer manifest.

    ``sha256`` maps an architecture to the hash of the built installer;
    an architecture without a hash is left out of the manifest entirely
    (winget rejects an installer whose hash is unknown), and
    :func:`validate` says which architectures are missing.
    """
    installers = []
    for arch in ARCHITECTURES:
        digest = (sha256 or {}).get(arch, "")
        if not digest:
            continue
        entry = {
            "Architecture": arch,
            "InstallerUrl": (urls or {}).get(arch) or installer_url(version, arch),
            "InstallerSha256": digest,
            "ProductCode": PRODUCT_CODE,
            "AppsAndFeaturesEntries": [
                {
                    "DisplayName": PACKAGE_NAME,
                    "Publisher": PUBLISHER,
                    "DisplayVersion": str(version),
                }
            ],
        }
        installers.append(entry)
    return {
        "PackageIdentifier": PACKAGE_IDENTIFIER,
        "PackageVersion": str(version),
        "InstallerLocale": LOCALE,
        "Platform": ["Windows.Desktop"],
        "MinimumOSVersion": "10.0.17763.0",
        "InstallerType": INSTALLER_TYPE,
        "Scope": "user",
        "InstallModes": ["interactive", "silent", "silentWithProgress"],
        "InstallerSwitches": {
            "Silent": SILENT_SWITCH,
            "SilentWithProgress": SILENT_WITH_PROGRESS_SWITCH,
            "Custom": CUSTOM_SWITCH,
        },
        "UpgradeBehavior": "install",
        "ReleaseDate": release_date or date.today().isoformat(),
        "Installers": installers,
        "ManifestType": "installer",
        "ManifestVersion": MANIFEST_VERSION,
    }


def locale_manifest(version: str, release_notes: str = "") -> dict:
    notes = " ".join(str(release_notes or "").split())
    if len(notes) > 10000:
        notes = notes[:9997] + "..."
    return {
        "PackageIdentifier": PACKAGE_IDENTIFIER,
        "PackageVersion": str(version),
        "PackageLocale": LOCALE,
        "Publisher": PUBLISHER,
        "PublisherUrl": PUBLISHER_URL,
        "PublisherSupportUrl": SUPPORT_URL,
        "Author": AUTHOR,
        "PackageName": PACKAGE_NAME,
        "PackageUrl": PROJECT_URL,
        "License": LICENSE,
        "LicenseUrl": LICENSE_URL,
        "Copyright": COPYRIGHT,
        "CopyrightUrl": LICENSE_URL,
        "ShortDescription": SHORT_DESCRIPTION,
        "Description": DESCRIPTION,
        "Moniker": MONIKER,
        "Tags": list(TAGS),
        "ReleaseNotes": notes or f"Release {version}.",
        "ReleaseNotesUrl": f"{RELEASES_URL}/tag/{release_tag(version)}",
        "ManifestType": "defaultLocale",
        "ManifestVersion": MANIFEST_VERSION,
    }


def build_all(version: str, sha256: dict | None = None, release_date: str = "",
              release_notes: str = "", urls: dict | None = None) -> dict:
    """All three manifests, keyed by file name."""
    return {
        f"{PACKAGE_IDENTIFIER}.yaml": version_manifest(version),
        f"{PACKAGE_IDENTIFIER}.installer.yaml": installer_manifest(
            version, sha256 or {}, release_date, urls
        ),
        f"{PACKAGE_IDENTIFIER}.locale.{LOCALE}.yaml": locale_manifest(
            version, release_notes
        ),
    }


# ---------------------------------------------------------------------------
# Validation (what winget's own validator checks, plus this project's rules)
# ---------------------------------------------------------------------------
def _strings(value) -> list:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [str(item) for item in value]
    return []


def _require(problems: list, data: dict, key: str, where: str) -> None:
    value = data.get(key)
    if value is None or (isinstance(value, str) and not value.strip()):
        problems.append(f"{where}: required field {key!r} is missing")


def validate(manifests: dict, version: str, sha256: dict | None = None,
             installer_exists: dict | None = None) -> list:
    """Return a list of winget-compliance problems (empty means compliant).

    ``manifests`` maps file name to the parsed manifest.  ``sha256`` maps an
    architecture to the hash of the installer that was actually built, so a
    manifest that points at a file whose bytes changed is reported.
    """
    problems: list = []
    names = {
        "version": f"{PACKAGE_IDENTIFIER}.yaml",
        "installer": f"{PACKAGE_IDENTIFIER}.installer.yaml",
        "locale": f"{PACKAGE_IDENTIFIER}.locale.{LOCALE}.yaml",
    }
    missing = [name for name in names.values() if name not in manifests]
    if missing:
        problems.append("missing manifest file(s): " + ", ".join(missing))
        return problems

    version_doc = manifests[names["version"]]
    installer_doc = manifests[names["installer"]]
    locale_doc = manifests[names["locale"]]

    # -- identity and version ------------------------------------------------
    for kind, doc in (("version", version_doc), ("installer", installer_doc),
                      ("locale", locale_doc)):
        _require(problems, doc, "PackageIdentifier", f"{kind} manifest")
        _require(problems, doc, "PackageVersion", f"{kind} manifest")
        _require(problems, doc, "ManifestType", f"{kind} manifest")
        _require(problems, doc, "ManifestVersion", f"{kind} manifest")
        if doc.get("PackageIdentifier") and not _IDENTIFIER_RE.match(
                str(doc["PackageIdentifier"])):
            problems.append(
                f"{kind} manifest: PackageIdentifier "
                f"{doc['PackageIdentifier']!r} is not a valid "
                "Publisher.PackageName identifier"
            )
        if doc.get("PackageVersion") != str(version):
            problems.append(
                f"{kind} manifest: PackageVersion {doc.get('PackageVersion')!r} "
                f"does not match the application version {version!r}"
            )
        if doc.get("ManifestVersion") != MANIFEST_VERSION:
            problems.append(
                f"{kind} manifest: ManifestVersion "
                f"{doc.get('ManifestVersion')!r} is not {MANIFEST_VERSION!r}"
            )

    identifiers = {
        doc.get("PackageIdentifier") for doc in
        (version_doc, installer_doc, locale_doc)
    }
    if len(identifiers) != 1:
        problems.append("the three manifests disagree about PackageIdentifier")

    if not _VERSION_RE.match(str(version)):
        problems.append(
            f"PackageVersion {version!r} must be dotted numbers only "
            "(winget sorts versions as numbers, not text)"
        )

    if version_doc.get("ManifestType") != "version":
        problems.append("version manifest: ManifestType must be 'version'")
    if installer_doc.get("ManifestType") != "installer":
        problems.append("installer manifest: ManifestType must be 'installer'")
    if locale_doc.get("ManifestType") != "defaultLocale":
        problems.append("locale manifest: ManifestType must be 'defaultLocale'")
    if version_doc.get("DefaultLocale") != LOCALE:
        problems.append(
            f"version manifest: DefaultLocale must be {LOCALE!r} and must "
            "match the locale manifest file name"
        )
    if locale_doc.get("PackageLocale") != LOCALE:
        problems.append(f"locale manifest: PackageLocale must be {LOCALE!r}")

    # -- locale metadata -----------------------------------------------------
    for key in ("Publisher", "PackageName", "License", "ShortDescription",
                "Description", "PackageUrl", "Moniker", "Tags"):
        _require(problems, locale_doc, key, "locale manifest")
    short = str(locale_doc.get("ShortDescription") or "")
    if len(short) > SHORT_DESCRIPTION_MAX:
        problems.append(
            f"locale manifest: ShortDescription is {len(short)} characters, "
            f"winget allows at most {SHORT_DESCRIPTION_MAX}"
        )
    description = str(locale_doc.get("Description") or "")
    if description and not DESCRIPTION_MIN <= len(description) <= DESCRIPTION_MAX:
        problems.append(
            f"locale manifest: Description must be {DESCRIPTION_MIN} to "
            f"{DESCRIPTION_MAX} characters (it is {len(description)})"
        )
    if locale_doc.get("License") and " " in str(locale_doc["License"]) and \
            not str(locale_doc["License"]).startswith("SPDX"):
        problems.append(
            f"locale manifest: License {locale_doc['License']!r} should be an "
            "SPDX expression (for example 'GPL-3.0-or-later')"
        )
    for url_key in ("PublisherUrl", "PublisherSupportUrl", "PackageUrl",
                    "LicenseUrl", "CopyrightUrl", "ReleaseNotesUrl"):
        value = str(locale_doc.get(url_key) or "")
        if value and not value.startswith("https://"):
            problems.append(
                f"locale manifest: {url_key} must be an https:// URL"
            )
    tags = locale_doc.get("Tags") or []
    if not isinstance(tags, list) or not tags:
        problems.append("locale manifest: Tags must be a non-empty list")
    else:
        for tag in tags:
            if not _TAG_RE.match(str(tag)):
                problems.append(
                    f"locale manifest: tag {tag!r} must be lowercase letters, "
                    "digits, and '-', '.', or '+' only"
                )
        if len(tags) > 20:
            problems.append("locale manifest: at most 20 tags are allowed")

    # -- installer -----------------------------------------------------------
    if installer_doc.get("InstallerType") != INSTALLER_TYPE:
        problems.append(
            f"installer manifest: InstallerType must be {INSTALLER_TYPE!r}"
        )
    if installer_doc.get("Scope") not in ("user", "machine"):
        problems.append(
            "installer manifest: Scope must be 'user' or 'machine' "
            "(the installer defaults to a per-user install)"
        )
    modes = _strings(installer_doc.get("InstallModes"))
    for needed in ("interactive", "silent", "silentWithProgress"):
        if needed not in modes:
            problems.append(
                f"installer manifest: InstallModes must include {needed!r}"
            )
    if installer_doc.get("UpgradeBehavior") != "install":
        problems.append(
            "installer manifest: UpgradeBehavior should be 'install' so a "
            "newer version replaces the installed one"
        )
    switches = installer_doc.get("InstallerSwitches") or {}
    if not isinstance(switches, dict):
        problems.append("installer manifest: InstallerSwitches must be a map")
        switches = {}
    if str(switches.get("Silent") or "").strip() != SILENT_SWITCH:
        problems.append(
            f"installer manifest: Silent switch must be {SILENT_SWITCH!r} "
            "(it is what winget runs, and what Inno Setup answers)"
        )
    if str(switches.get("SilentWithProgress") or "").strip() != \
            SILENT_WITH_PROGRESS_SWITCH:
        problems.append(
            "installer manifest: SilentWithProgress switch must be "
            f"{SILENT_WITH_PROGRESS_SWITCH!r}"
        )
    release_date = str(installer_doc.get("ReleaseDate") or "")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", release_date):
        problems.append(
            "installer manifest: ReleaseDate must be an ISO date (YYYY-MM-DD)"
        )
    else:
        try:
            if datetime.strptime(release_date, "%Y-%m-%d").date() > date.today():
                problems.append(
                    "installer manifest: ReleaseDate is in the future"
                )
        except ValueError:
            problems.append("installer manifest: ReleaseDate is not a real date")

    installers = installer_doc.get("Installers") or []
    if not isinstance(installers, list) or not installers:
        problems.append("installer manifest: Installers must not be empty")
        installers = []
    seen_arches = set()
    for entry in installers:
        if not isinstance(entry, dict):
            problems.append("installer manifest: every Installers entry is a map")
            continue
        arch = str(entry.get("Architecture") or "")
        if arch not in ARCHITECTURES:
            problems.append(
                f"installer manifest: Architecture {arch!r} must be one of "
                + ", ".join(ARCHITECTURES)
            )
        if arch in seen_arches:
            problems.append(
                f"installer manifest: Architecture {arch!r} is listed twice"
            )
        seen_arches.add(arch)

        url = str(entry.get("InstallerUrl") or "")
        if not url.startswith("https://"):
            problems.append(
                f"installer manifest ({arch}): InstallerUrl must be an "
                "https:// URL"
            )
        elif "/latest" in url or url.rstrip("/").endswith("/releases"):
            problems.append(
                f"installer manifest ({arch}): InstallerUrl must point at a "
                "versioned release asset, not a 'latest' redirect"
            )
        elif _VERSION_RE.match(str(version)) and \
                f"/download/{release_tag(version)}/" not in url:
            problems.append(
                f"installer manifest ({arch}): InstallerUrl must be the asset "
                f"of release {release_tag(version)}"
            )
        elif arch and installer_filename(version, arch) not in url:
            problems.append(
                f"installer manifest ({arch}): InstallerUrl should name "
                f"{installer_filename(version, arch)!r}"
            )

        digest = str(entry.get("InstallerSha256") or "")
        if not _SHA256_RE.match(digest):
            problems.append(
                f"installer manifest ({arch}): InstallerSha256 must be 64 "
                "uppercase hex characters"
            )
        elif sha256 and arch in sha256 and sha256[arch] != digest:
            problems.append(
                f"installer manifest ({arch}): InstallerSha256 does not match "
                "the installer that was built"
            )
        if installer_exists and arch in installer_exists and \
                not installer_exists[arch] and digest:
            problems.append(
                f"installer manifest ({arch}): an installer hash is published "
                "but no installer was built for this architecture"
            )

        if str(entry.get("ProductCode") or "") != PRODUCT_CODE:
            problems.append(
                f"installer manifest ({arch}): ProductCode must be "
                f"{PRODUCT_CODE!r} (the Inno Setup uninstall key), otherwise "
                "winget cannot tell an installed copy from a fresh install"
            )
        entries = entry.get("AppsAndFeaturesEntries") or []
        if not entries:
            problems.append(
                f"installer manifest ({arch}): AppsAndFeaturesEntries should "
                "name the 'Apps and features' entry"
            )
    for arch in ARCHITECTURES:
        if sha256 and arch in sha256 and sha256[arch] and arch not in seen_arches:
            problems.append(
                f"installer manifest: an installer was built for {arch} but no "
                "Installers entry publishes it"
            )
    return problems


# ---------------------------------------------------------------------------
# A very small YAML subset: writer and reader
# ---------------------------------------------------------------------------
_KEYWORD_SCALARS = {"true", "false", "null", "yes", "no", "on", "off", "~"}


def _escape(text: str) -> str:
    return (text.replace("\\", "\\\\").replace('"', '\\"')
            .replace("\n", "\\n").replace("\t", "\\t"))


def _unescape(text: str) -> str:
    out: list = []
    index = 0
    while index < len(text):
        char = text[index]
        if char == "\\" and index + 1 < len(text):
            following = text[index + 1]
            out.append({"n": "\n", "t": "\t", "\\": "\\", '"': '"'}
                       .get(following, following))
            index += 2
            continue
        out.append(char)
        index += 1
    return "".join(out)


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text == "":
        return '""'
    first = text[0]
    needs_quotes = (
        text != text.strip()
        or ": " in text
        or " #" in text
        or "\n" in text
        or "\t" in text
        or "\\" in text
        or first in "-?:,[]{}#&*!|>'\"%@`"
        or text.lower() in _KEYWORD_SCALARS
    )
    if not needs_quotes:
        return text
    return '"' + _escape(text) + '"'


def dump_yaml(data, indent: int = 0) -> str:
    """Write ``data`` (maps, lists, scalars) as YAML text."""
    pad = " " * indent
    lines = []
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, dict) and value:
                lines.append(f"{pad}{key}:")
                lines.append(dump_yaml(value, indent + 2))
            elif isinstance(value, list) and value:
                lines.append(f"{pad}{key}:")
                lines.append(dump_yaml(value, indent + 2))
            elif isinstance(value, dict):
                lines.append(f"{pad}{key}: {{}}")
            elif isinstance(value, list):
                lines.append(f"{pad}{key}: []")
            else:
                lines.append(f"{pad}{key}: {_scalar(value)}")
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict) and item:
                inner = dump_yaml(item, indent + 2)
                first = inner.splitlines()[0].strip()
                lines.append(f"{pad}- {first}")
                lines.extend(inner.splitlines()[1:])
            elif isinstance(item, list) and item:
                lines.append(f"{pad}-")
                lines.append(dump_yaml(item, indent + 2))
            else:
                lines.append(f"{pad}- {_scalar(item)}")
    else:
        lines.append(f"{pad}{_scalar(data)}")
    return "\n".join(lines)


def _strip_comment(line: str) -> str:
    out: list = []
    quote = ""
    for char in line:
        if quote:
            out.append(char)
            if char == quote:
                quote = ""
        elif char in "\"'":
            quote = char
            out.append(char)
        elif char == "#" and (not out or out[-1] in " \t"):
            break
        else:
            out.append(char)
    return "".join(out).rstrip()


def _parse_scalar(text: str):
    text = text.strip()
    if len(text) >= 2 and text[0] == text[-1] == '"':
        return _unescape(text[1:-1])
    if len(text) >= 2 and text[0] == text[-1] == "'":
        return text[1:-1].replace("''", "'")
    low = text.lower()
    if low in ("true", "false"):
        return low == "true"
    if low in ("null", "~", ""):
        return None
    try:
        return int(text)
    except ValueError:
        return text


def _split_pair(text: str) -> tuple:
    quote = ""
    for index, char in enumerate(text):
        if quote:
            if char == quote:
                quote = ""
        elif char in "\"'":
            quote = char
        elif char == ":":
            return text[:index].strip(), text[index + 1:].strip()
    return text.strip(), None


def _parse_block(lines: list, index: int, indent: int):
    if index >= len(lines) or lines[index][0] < indent:
        return {}, index
    if lines[index][1].startswith("-"):
        return _parse_list(lines, index, indent)
    return _parse_map(lines, index, indent)


def _parse_map(lines: list, index: int, indent: int):
    result: dict = {}
    while index < len(lines) and lines[index][0] == indent:
        text = lines[index][1]
        if text.startswith("-"):
            break
        key, rest = _split_pair(text)
        index += 1
        if rest is None or rest == "":
            if index < len(lines) and lines[index][0] > indent:
                value, index = _parse_block(lines, index, lines[index][0])
            else:
                value = {}
        else:
            value = _parse_scalar(rest)
        result[key] = value
    return result, index


def _parse_list(lines: list, index: int, indent: int):
    items: list = []
    while index < len(lines) and lines[index][0] == indent and \
            lines[index][1].startswith("-"):
        content = lines[index][1][1:].strip()
        index += 1
        if not content:
            if index < len(lines) and lines[index][0] > indent:
                item, index = _parse_block(lines, index, lines[index][0])
            else:
                item = None
        else:
            key, rest = _split_pair(content)
            # "- Architecture: x64" is a map entry; "- https://a/b" is a
            # scalar that happens to contain a colon.
            if rest is None or "/" in key or " " in key:
                item = _parse_scalar(content)
            else:
                # An inline map entry: "- Architecture: x64" and whatever
                # deeper lines belong to it.
                inline = [(indent + 2, content)]
                while index < len(lines) and lines[index][0] > indent:
                    inline.append(lines[index])
                    index += 1
                item, _ = _parse_map(inline, 0, indent + 2)
        items.append(item)
    return items, index


def load_yaml(text: str):
    """Read back what :func:`dump_yaml` writes (plus hand edits of the same shape)."""
    lines: list = []
    for raw in text.splitlines():
        stripped = _strip_comment(raw)
        if not stripped.strip():
            continue
        lines.append((len(stripped) - len(stripped.lstrip(" ")), stripped.strip()))
    if not lines:
        return {}
    value, _ = _parse_block(lines, 0, lines[0][0])
    return value


def load_manifests(folder: str) -> dict:
    """Read the three manifests of ``folder``, keyed by file name."""
    result: dict = {}
    for name in (
        f"{PACKAGE_IDENTIFIER}.yaml",
        f"{PACKAGE_IDENTIFIER}.installer.yaml",
        f"{PACKAGE_IDENTIFIER}.locale.{LOCALE}.yaml",
    ):
        path = os.path.join(folder, name)
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as handle:
                result[name] = load_yaml(handle.read())
    return result
